# Generated by Django 3.0.6 on 2020-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200518_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.TextField(),
        ),
    ]
